trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build_And_Test
    displayName: Build And Test
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            inputs:
              filePath: './scripts/run.sh'
              arguments: 'ut'
        # - task: Docker@2
        #   displayName: Build an image
        #   inputs:
        #     command: build
        #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        #     tags: |
        #       $(tag)
