trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build_And_Test
    displayName: Build And Test
    jobs:
      - job: test
        displayName: run test
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            inputs:
              filePath: './scripts/run.sh'
              arguments: 'ut'
      - job: build_docker_image
        dependsOn: test
        condition: succeeded()
        displayName: build docker image
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'acr'
              repository: 'webapp'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              buildContext: '.'
          - task: Docker@2
            inputs:
              containerRegistry: 'acr'
              repository: 'migration'
              command: 'buildAndPush'
              Dockerfile: './Migration/Dockerfile'
              buildContext: './Migration'
  - stage: Deploy_To_Dev
      displayName: Deploy To Dev
      jobs:
        - job: migration
            displayName: run db migration
            pool:
              vmImage: 'ubuntu-latest'
            steps:
              - task: Bash@3
                inputs:
                  filePath: './scripts/run.sh'
                  arguments: 'ut'