version: "3.8"
services:
  sql:
    image: webapp-sql:latest
    build: data
    container_name: webapp-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD} # https://hub.docker.com/_/microsoft-mssql-server requires use of SA_PASSWORD
      - DATABASE_NAME=${DATABASE_NAME}

  migration:
    image: migration:latest
    build: Migration
    container_name: webapp-sql-migration
    depends_on:
      - sql
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SERVER=${DATABASE_SERVER}

  test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    depends_on:
      - sql
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - bash
      - -c
      - |
          dotnet restore
          dotnet test WebApp.Test/WebApp.Test.csproj
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SERVER=${DATABASE_SERVER}